### ISSUE TITLE
No module named prosr

### ISSUE THREAD

**Issue by nazariyv** [fperazzi/proSR#8]
Hi,

I have installed all of the dependencies. Then I added prosr to the path like so:

``export PYTHONPATH=/home/nazariy/git/proSR/lib/prosr/__init__.py``

However, when I run test script:

``python test.py --checkpoint data/checkpoints/proSR.pth --target data/datasets/DIV2K/DIV2K_valid_HR --scale 8``

I get the following error:

``Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from prosr import Phase
ModuleNotFoundError: No module named 'prosr'``

**Comment by hromadka** [comment]
try using the full path for $PROJECT_ROOT in PYTHONPATH, e.g.:
 export PYTHONPATH=/home/username/workspace/proSR/lib:$PYTHONPATH

**Comment by fperazzi** [comment]
export PYTHONPATH=/home/nazariy/git/proSR/lib

**Comment by adamantek** [comment]
I'm having the same module not found issue. I run `export PYTHONPATH=/home/ryan/Downloads/proSR` this is the path of the proSR pretrained models folder I unzipped.

**Comment by scotshinderman** [comment]
@adamantek   set the PYTHONPATH to were the lib directory is (this environment variable is needed by python to find the code for the module).      in the data directory there's a shell script that will download the pretrained models (or if it's already downloaded just copy into there --- the script might be better just because it has the directory layout ready to go)   hth

**Comment by JesperHenriksen** [comment]
Moving the prosr folder out of lib folder works aswell
